### ISSUE TITLE
Error build on debian 10

### ISSUE THREAD

**Issue by kleyton67** [maroviher/DPO_RT5572_LinuxSTA_2.6.1.3_20121022_mod#4]
I have a problem on build project, on  DPO_RT5572_LinuxSTA_2.6.1.3_20121022_mod-master/DPO_RT5572_LinuxSTA_2.6.1.3_20121022:

$ sudo make

> /home/dragao/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022_mod-master/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/os/linux/../../sta/sta_cfg.c: In function ‘set_quality’:
/home/dragao/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022_mod-master/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/os/linux/../../sta/sta_cfg.c:5548:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  BOOLEAN bInitial = FALSE;
  ^~~~~~~
/home/dragao/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022_mod-master/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/os/linux/../../sta/sta_cfg.c: In function ‘RtmpIoctl_rt_ioctl_giwrate’:
/home/dragao/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022_mod-master/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/os/linux/../../sta/sta_cfg.c:7098:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if (rate_index >= rate_count)
     ^~
/home/dragao/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022_mod-master/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/os/linux/../../sta/sta_cfg.c:7101:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  *(ULONG *)pData = ralinkrate[rate_index] * 500000;
  ^
  CC [M]  /home/dragao/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022_mod-master/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/os/linux/../../common/rt_os_util.o
  CC [M]  /home/dragao/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022_mod-master/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/os/linux/../../os/linux/sta_ioctl.o
In file included from /usr/src/linux-headers-4.19.0-4-common/include/linux/bitmap.h:9,
                 from /usr/src/linux-headers-4.19.0-4-common/include/linux/cpumask.h:12,
                 from /usr/src/linux-headers-4.19.0-4-common/arch/x86/include/asm/cpumask.h:5,
                 from /usr/src/linux-headers-4.19.0-4-common/arch/x86/include/asm/msr.h:11,
                 from /usr/src/linux-headers-4.19.0-4-common/arch/x86/include/asm/processor.h:21,
                 from /usr/src/linux-headers-4.19.0-4-common/arch/x86/include/asm/cpufeature.h:5,
                 from /usr/src/linux-headers-4.19.0-4-common/arch/x86/include/asm/thread_info.h:53,
                 from /usr/src/linux-headers-4.19.0-4-common/include/linux/thread_info.h:38,
                 from /usr/src/linux-headers-4.19.0-4-common/arch/x86/include/asm/preempt.h:7,
                 from /usr/src/linux-headers-4.19.0-4-common/include/linux/preempt.h:81,
                 from /usr/src/linux-headers-4.19.0-4-common/include/linux/spinlock.h:51,
                 from /usr/src/linux-headers-4.19.0-4-common/include/linux/seqlock.h:36,
                 from /usr/src/linux-headers-4.19.0-4-common/include/linux/time.h:6,
                 from /usr/src/linux-headers-4.19.0-4-common/include/linux/stat.h:19,
                 from /usr/src/linux-headers-4.19.0-4-common/include/linux/module.h:10,
                 from /home/dragao/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022_mod-master/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/include/os/rt_linux.h:31,
                 from /home/dragao/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022_mod-master/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/include/rtmp_os.h:44,
                 from /home/dragao/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022_mod-master/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/include/rtmp_comm.h:69,
                 from /home/dragao/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022_mod-master/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/os/linux/../../os/linux/sta_ioctl.c:30:
In function ‘memcpy’,
    inlined from ‘rt_ioctl_iwaplist’ at /home/dragao/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022_mod-master/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/os/linux/../../os/linux/sta_ioctl.c:697:2:
/usr/src/linux-headers-4.19.0-4-common/include/linux/string.h:341:4: error: call to ‘__read_overflow2’ declared with attribute error: detected read beyond size of object passed as 2nd parameter
    __read_overflow2();
    ^~~~~~~~~~~~~~~~~~
make[4]: *** [/usr/src/linux-headers-4.19.0-4-common/scripts/Makefile.build:309: /home/dragao/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022_mod-master/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/os/linux/../../os/linux/sta_ioctl.o] Error 1
make[3]: *** [/usr/src/linux-headers-4.19.0-4-common/Makefile:1535: _module_/home/dragao/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022_mod-master/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/os/linux] Error 2
make[2]: *** [Makefile:146: sub-make] Error 2
make[1]: *** [Makefile:8: all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.0-4-amd64'

$ uname -a

> 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux

$ cat /etc/issue

> Debian GNU/Linux 10

$ lspci

> ... 

$ lsusb

> Bus 002 Device 002: ID 148f:5572 Ralink Technology, Corp. RT5572 Wireless Adapter

If you need any more information, I will be at your disposal.

**Comment by maroviher** [comment]
Try my last commit. This issue was fixed. But there is another issue with init_timers. Looks like a Kernel API has changed a bit. You are welcome to contribute, to fix that.
