### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ShashaankHari** [maroviher/DPO_RT5572_LinuxSTA_2.6.1.3_20121022_mod#6]
I Have Leoxsys HG150N with Ralink chipset, I'm confused in the installation of official drivers the provided by the company. Can you please guide me in installing the drivers? The drivers the provide, have 4 zips inside and I really need help. One of the zips is rt5572 which has rt2860.dat. Inside the doc folder the instructions are confusing
![image](https://user-images.githubusercontent.com/16036514/116554179-84f6ad00-a918-11eb-8286-46e51d8689b4.png)

**Comment by maroviher** [comment]
Under Linux you do not install drivers, but compile these from source.
